//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.10 at 11:08:26 AM ICT 
//


package com.andrewxyz.ws.authdirect;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.andrewxyz.ws.authdirect package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.andrewxyz.ws.authdirect
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OtpRequest }
     * 
     */
    public OtpRequest createOtpRequest() {
        return new OtpRequest();
    }

    /**
     * Create an instance of {@link AuthResponse }
     * 
     */
    public AuthResponse createAuthResponse() {
        return new AuthResponse();
    }

    /**
     * Create an instance of {@link ClientAuthRequest }
     * 
     */
    public ClientAuthRequest createClientAuthRequest() {
        return new ClientAuthRequest();
    }

    /**
     * Create an instance of {@link AuthRequest }
     * 
     */
    public AuthRequest createAuthRequest() {
        return new AuthRequest();
    }

    /**
     * Create an instance of {@link OtpResponse }
     * 
     */
    public OtpResponse createOtpResponse() {
        return new OtpResponse();
    }

    /**
     * Create an instance of {@link ClientAuthResponse }
     * 
     */
    public ClientAuthResponse createClientAuthResponse() {
        return new ClientAuthResponse();
    }

}
